language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - sed -i '/"dependencies":\ {/i"homepage":\ "https://samitc.github.io/bus-times/",' package.json
  - SRC="const BASE_URL = '";DST="const BASE_URL = '$SERVER_URL';";sed -i "s^$SRC.*^$DST^" src/data/Buses.js
  - npm run build
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  committer_from_gh: true
  target_branch: gh-pages
  on:
    branch: master
